### ISSUE TITLE
hinge_loss value is never 0

### ISSUE THREAD

**Issue by Gnumlab** [Gnumlab/JuliaWIP#1]
I checked Flux implementation of the algorithm in MNIST_flux and found out that hinge_loss minimum is 0.9 as well as the loss of the trained model.
I think there is a bug in how the hinge loss is used: perhaps one hot encoded should be better use (?)

**Comment by natema** [comment]
What's the update on this?

**Comment by Gnumlab** [comment]
The problem does not arise in SimpleChains' implementation of the algorithm. The issue lies in the generation of the train loader and the requirement for one-hot encoding.
I am closing the issue because the problem does not occur when using SimpleChains.
